# Generated by Django 3.2.18 on 2025-04-11 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=40, null=True)),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('product_location', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, choices=[('CEREALS', 'Cereals'), ('LEGUMES', 'Legumes'), ('ROOTS_TUBERS', 'Roots and Tubers'), ('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('NUTS_SEEDS', 'Nuts and Seeds'), ('LIVESTOCK', 'Livestock'), ('LIVESTOCK_PRODUCTS', 'Livestock Products'), ('POULTRY', 'Poultry'), ('FISH', 'Fish'), ('HERBS_SPICES', 'Herbs and Spices'), ('OIL_CROPS', 'Oil Crops'), ('FIBER_CROPS', 'Fiber Crops'), ('FORESTRY_PRODUCTS', 'Forestry Products'), ('OTHER', 'Other')], default='OTHER', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mfarm.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_created=True, blank=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mfarm.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mfarm.product')),
            ],
        ),
    ]
