# Generated by Django 5.2 on 2025-04-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0003_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
