# Generated by Django 5.2 on 2025-04-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
