# Generated by Django 5.2 on 2025-04-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
