# Generated by Django 3.2.18 on 2025-04-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0012_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='placed_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='placed_by_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
