# Generated by Django 3.2.18 on 2025-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0013_auto_20250421_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.AddField(
            model_name='product',
            name='user_username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
