# Generated by Django 5.2.1 on 2025-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0014_auto_20250427_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
