# Generated by Django 5.2.1 on 2025-06-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0015_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.CharField(blank=True, null=True),
        ),
    ]
