# Generated by Django 5.2.1 on 2025-06-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0016_alter_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_id',
        ),
    ]
