# Generated by Django 5.2.1 on 2025-06-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0017_rename_user_product_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
    ]
