# Generated by Django 5.2.1 on 2025-06-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0018_alter_product_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='placed_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
