# Generated by Django 5.2.1 on 2025-06-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0020_remove_productorder_placed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
