# Generated by Django 5.2.1 on 2025-07-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfarm', '0021_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
