# Generated by Django 5.2.1 on 2025-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
