# Generated by Django 5.2.1 on 2025-07-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_order_rename_created_at_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transsaction_id',
            new_name='transaction_id',
        ),
    ]
