"""
Django settings for accounts project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=c(@)*_b2l^!ov5+1ahfkh+@r*iss7nm9&5y*xwb$o)drkn-um'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


#CORS ALLOW ORIGIN
CORS_ALLOWED_ORIGINS = ['http://localhost:3000','http://localhost:8000','http://localhost:8002']

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "unfold",  
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #3rd party apps
    'django.contrib.sites',  # Required for django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',
    #3rd party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'dj_rest_auth.registration',
    'dj_rest_auth',

    #local apps
    "accs.apps.AccsConfig",
]

JAZZMIN_UI_TWEAKS = {
    "theme": "slate",
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SITE_ID = 1

#all auth settings
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300

#social auth specififc setitngs
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

#define the social auth providers

SOCIALACCOUNT_PROVIDERS = {
    'google':{
        'APP':{
            'client_id':os.getenv('GOOGLE_CLIENT_ID'),
            "secret":os.getenv('GOOGLE_CLIENT_SECRET'),
        },
        'SCOPE':[
            'profile',
            'email',
        ],
        'AUTH_PARAMS':{
            'access_type':'online',
        }
    },
    'facebook':{
        "APP":{
            'client_id':'FACEBOOK_CLIENT_ID',
            'secret':'FACEBOOK_CLIENT_SECRET',
        },
        'METHOD':'oauth2',
        'SCOPE':[
            'profile',
            'email',
        ],
        'AUTH_PARAMS':{
            'auth_type':'reauthenticate',
        }
    },
    'github':{
        'APP':{
            'client_id':'GITHUB_CLIENT_ID',
            'secret':'GITHUB_CLIENT_SECRET',
        },
        'SCOPE':[
            'user:email',
            'read:ser',
        ]
    }
}


ROOT_URLCONF = 'accounts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accounts.wsgi.application'

SPECTACULAR_SETTINGS = {
    'TITLE': 'M-Farm Accounts App API Docs',
    'DESCRIPTION': 'API for M-FARM agricultural marketplace',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        # 'HOST': os.getenv("AWS_RDS_ENDPOINT"),
        "HOST":os.getenv("DB_HOST"),
        'PORT': '5432',
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}


# password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accs.CustomUser'

# REST Framework settings (for JWT, consistent with FarmerDashboard)
#DRF SETTINGS
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny', 
    ],
     'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/day', 
        'user': '1000/hour', #rate limitting to the API endpoints per user per hour.
    },
}

REST_AUTH = {
    'USE_JWT':True,
    'JWT_AUTH_HTTPONLY':False,
    'JWT_AUTH_COOKIE':'access_token',
    'JWT_AUTH_REFRESH_COOKIE':'refrest_token',
    'SOCIAL_ACCOUNT_ADAPTER':'accounts.accounts.adapter.CustomSocialAccountAdapter',
}

SOCIALACCOUNT_LOGIN_REDIRECT_URL = 'http://localhost:3000/signup'

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=360),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY'),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN':True,
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'
# settings.py

STATICFILES_DIRS = [BASE_DIR / "static"]  
STATIC_ROOT = BASE_DIR / "staticfiles"    

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "static/uploads"  

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py

UNFOLD = {
    "SITE_HEADER": "M-Farm Accounts Admin Panel",
    "SITE_TITLE": "M-Farm Admin",
    "INDEX_TITLE": "Welcome to the Accounts Admin Dashboard",
    "UNFOLD_LOGO": "/static/img/my_logo.svg",
    "UNFOLD_FAVICONS": [
        lambda request: {"href": "/static/img/favicon.ico", "sizes": "16x16", "type": "image/x-icon"}
    ],
    # "COLORS": {
    #     "primary": "#0D7E22", 
        
    # },
    "DARK_MODE_ENABLED": True, # Enable/disable dark mode switcher
    "SIDEBAR": {
        "show_search": True, # Show search box in sidebar
        "show_all_applications": True, # Show all apps in sidebar
        "navigation": [
            {
                "title": "Navigation",
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard", # Material Symbols icon name
                        "link": "admin:index",
                    },
                    {
                        "title": "My Custom Page",
                        "icon": "auto_awesome",
                        "link": "/admin/my_custom_page/", # Link to a custom admin URL
                    },
                    # Add more items or groups of items
                    {
                        "title": "App Management",
                        "separator": True, # Adds a separator above this section
                        "items": [
                            {
                                "title": "Products",
                                "icon": "shopping_bag",
                                "link": "admin:myapp_product_changelist", # Format: admin:appname_modelname_changelist
                            },
                            {
                                "title": "Categories",
                                "icon": "category",
                                "link": "admin:myapp_category_changelist",
                            },
                        ]
                    }
                ],
            },
        ],
    },
    # # Add custom CSS or JS globally
    # "STYLES": [
    #     lambda request: static("css/my_custom_admin.css"),
    # ],
    # "SCRIPTS": [
    #     lambda request: static("js/my_custom_admin.js"),
    # ],
    # # You can also configure a DASHBOARD_CALLBACK to pass custom data to the admin dashboard
    # # "DASHBOARD_CALLBACK": "path.to.your.dashboard_callback_function",
}