# Generated by Django 5.2.1 on 2025-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('specialty', models.CharField(max_length=70)),
                ('booked_date', models.DateField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
    ]
