apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: m-farm-api-ingress
  namespace: default 
  annotations:
    #  AWS Load Balancer Controller to provision an ALB
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing 
    alb.ingress.kubernetes.io/target-type: ip 
    alb.ingress.kubernetes.io/backend-protocol: HTTP 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]' 

    # You might want HTTPS later, which requires an ACM Certificate ARN.
    # If you add HTTPS, uncomment these and replace with your ARN:
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:123456789012:certificate/your-certificate-id
    # alb.ingress.kubernetes.io/ssl-redirect: '443' # Redirect HTTP to HTTPS
spec:
  rules:
  - http:
      paths:
      - path: /accounts/* 
        pathType: Prefix
        backend:
          service:
            name: m-farm-user-service 
            port:
              number: 8001 
      - path: /payment/* 
        pathType: Prefix
        backend:
          service:
            name: m-farm-payment-service 
            port:
              number: 8002 
      - path: /products/* 
        pathType: Prefix
        backend:
          service:
            name: m-farm-product-service 
            port:
              number: 8000 