# k8s-manifests/product-service-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfarm-product-service 
  namespace: default 
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: mfarm-product-service
  template:
    metadata:
      labels:
        app: mfarm-product-service
    spec:
     
      initContainers:
        - name: migrate-product-db
          
          image: 740857577909.dkr.ecr.us-east-1.amazonaws.com/m-farm-m-farm-product-service:${{ github.sha }} 
         
          command: ["python3", "manage.py", "migrate", "--noinput"]
          envFrom: # Load environment variables from ConfigMap and Secret
            - configMapRef:
                name: mfarm-product-config # Reference the ConfigMap
            - secretRef:
                name: mfarm-product-secrets # Reference the Secret
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"

      containers:
      - name: mfarm-product-service
        image: 740857577909.dkr.ecr.us-east-1.amazonaws.com/m-farm-m-farm-product-service:${{ github.sha }} 
        ports:
        - containerPort: 8000 
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom: # Load environment variables from ConfigMap and Secret
          - configMapRef:
              name: mfarm-product-config # Reference the ConfigMap
          - secretRef:
              name: mfarm-product-secrets # Reference the Secret
        livenessProbe:
          httpGet:
            path: /health # Ensure your Django app has a /health endpoint
            port: 8000 # Adjust this port to your Django app's actual port
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health # Ensure your Django app has a /health endpoint
            port: 8000 # Adjust this port to your Django app's actual port
          initialDelaySeconds: 5
          periodSeconds: 5