# k8s-manifests/product-service-config-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mfarm-product-secrets # Named for the product service
  namespace: default # Ensure this matches your deployment namespace
stringData:
  # AWS Prod DB Password
  db_password: "securepassword" # Your DBPASSWORD for the product service
  # JWT Secret
  jwt_secret_key: "rD5xLkAblBUqUCbKbihNYkxtX4534xxm8uuwyt9cDAJHycX386GYYdC9r91OvAG13CU"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mfarm-product-config # Named for the product service
  namespace: default # Ensure this matches your deployment namespace
data:
  # AWS Prod DB Configuration
  db_name: "mfarm-product" # DBNAME for the product service
  db_user: "john"         # DBUSER for the product service
  db_host: "m-farm-product.cq32e02eaaeq.us-east-1.rds.amazonaws.com" # AWS_RDS_ENDPOINT for the product service
  db_port: "5432"         # Default PostgreSQL port